from fastapi import APIRouter, HTTPException
from models.schemas import QueryRequest, QueryResponse
from services.gemini_service import generate_sql
from services.db_service import get_schema_string, execute_query

router = APIRouter()


@router.post("/query", response_model=QueryResponse)
async def handle_query(request: QueryRequest):
    try:
        print("📥 Incoming request:", request)   # 👈 ADD THIS

        schema = get_schema_string()

        sql = generate_sql(request.question, schema)

        print("🧠 Generated SQL:", sql)         # 👈 ADD THIS

        explanation = "Generated by AI"
        confidence = 1.0

        try:
            columns, results = execute_query(sql)
        except Exception as e:
            print("❌ SQL ERROR:", e)            # 👈 THIS IS KEY
            raise HTTPException(
                status_code=400,
                detail=f"Invalid SQL generated: {str(e)}"
            )

        return QueryResponse(
            question=request.question,
            sql=sql,
            explanation=explanation,
            confidence=confidence,
            columns=columns,
            results=results,
            row_count=len(results),
        )

    except Exception as e:
        print("🔥 SERVER ERROR:", e)
        raise HTTPException(status_code=500, detail=str(e))