from fastapi import APIRouter, HTTPException
from models.schemas import QueryRequest, QueryResponse
from services.gemini_service import generate_sql
from services.db_service import get_schema_string, execute_query

router = APIRouter()


@router.post("/query", response_model=QueryResponse)
async def handle_query(request: QueryRequest):
    try:
        # Step 1: Get schema
        schema = get_schema_string()

        # Step 2: Generate SQL (NO await ❗)
        sql = generate_sql(request.question, schema)

        # Dummy values (since Groq returns only SQL)
        explanation = "Generated by AI"
        confidence = 1.0

        # Step 3: Execute query safely
        try:
            columns, results = execute_query(sql)
        except Exception as e:
            print("SQL ERROR:", e)
            raise HTTPException(
                status_code=400,
                detail=f"Invalid SQL generated: {str(e)}"
            )

        return QueryResponse(
            question=request.question,
            sql=sql,
            explanation=explanation,
            confidence=confidence,
            columns=columns,
            results=results,
            row_count=len(results),
        )

    except HTTPException:
        raise
    except Exception as e:
        print("SERVER ERROR:", e)
        raise HTTPException(status_code=500, detail=f"Internal error: {str(e)}")